CREATE TABLE IF NOT EXISTS up_tasks_task
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	RESPONSIBLE_ID INT NOT NULL,
	PRIORITY_ID INT NOT NULL,
	STATUS_ID INT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS up_tasks_responsible
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS up_tasks_priority
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(60) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS up_tasks_status
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(60) NOT NULL,
	PRIMARY KEY(ID)
);